spring.application.name=clarkasn2

server.tomcat.accesslog.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-d6ad47oboq4c73f98hk0-a.virginia-postgres.render.com/database_4gw2
spring.datasource.username=database_4gw2_user
spring.datasource.password=5pDD8VdxVMTTz1dHVCItwFQQsk7nWBGL